### ISSUE TITLE
Specify supported versions of Node.js in package.json

### ISSUE THREAD

**Issue by d4nyll** [itwillwork/ostap#4]
Just tried this using Node.js `v7.9.0`

```
$ ostap ./package.json -d
/home/dli/.config/yarn/global/node_modules/ostap/cli.js:89
    let options = { ...DEFAULT_OPTIONS };
                    ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
```

Working fine with the latest version of Node.js (`v11.11.0`)

```
$ nvm use node
Now using node v11.11.0 (npm v6.7.0)
d4nyll:~/projects/conversation-service/service$ ostap ./package.json -d
✔ source tree: zero duplicates


🎉 well done! zero duplicates


✔ done, 0.859s
✔ optimal tree: zero duplicates
well done, not found duplicates
bye
```

It'll be a good idea to specify [`engines`](https://docs.npmjs.com/files/package.json#engines) in your `package.json` to indicated the supported versions of Node.js

**Comment by itwillwork** [comment]
Thanks! good idea
https://github.com/itwillwork/ostap/commit/31c4fcbbc90a1d8430849e987a8f359d2c22276d
```
npm i -g ostap@1.0.3
```
